"""add auth fields to user table

Revision ID: 830e7523b7b1
Revises: 
Create Date: 2026-09-18 22:38:25.439021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '830e7523b7b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # SQLite doesn't support ALTER COLUMN, so we add with defaults and will enforce NOT NULL at app level
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))  # Will be populated
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='1'))
    op.add_column('users', sa.Column('is_organic', sa.Boolean(), server_default='0'))
    # Note: Email constraint is managed at application level via Pydantic EmailStr


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'is_organic')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
